/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab1_java3_31102023;

import javax.swing.JOptionPane;

/**
 *
 * @author Hawin
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    public void traHam(String so1, String so2) {
        if (so1.equals("")) {
            so1 = "0";
        }
        if (so2.equals("")) {
            so2 = "0";
        }
        float num1 = Float.parseFloat(so1);
        float num2 = Float.parseFloat(so2);
        float ketQua = num1 + num2;
        txtKetQua.setText(ketQua + "");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtso1 = new javax.swing.JTextField();
        txtso2 = new javax.swing.JTextField();
        txtKetQua = new javax.swing.JTextField();
        btnCong = new javax.swing.JButton();
        btnTru = new javax.swing.JButton();
        btnNhan = new javax.swing.JButton();
        btnChia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("First number");

        jLabel2.setText("Second number");

        jLabel3.setText("Result");

        btnCong.setText("+");
        btnCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCongMouseClicked(evt);
            }
        });

        btnTru.setText("-");
        btnTru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTruMouseClicked(evt);
            }
        });

        btnNhan.setText("*");
        btnNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhanMouseClicked(evt);
            }
        });

        btnChia.setText("/");
        btnChia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChiaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(btnCong)))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtso1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtso2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTru)
                        .addGap(32, 32, 32)
                        .addComponent(btnNhan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChia)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCong)
                    .addComponent(btnTru)
                    .addComponent(btnNhan)
                    .addComponent(btnChia))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCongMouseClicked
        try {
            String so1 = txtso1.getText();
            String so2 = txtso2.getText();
            if (so1.equals("") || so1.isEmpty() || so2.equals("") || so2.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please input your name");
            } else {
                float num1 = Float.parseFloat(so1);
                float num2 = Float.parseFloat(so2);
                float ketQua = num1 + num2;
                txtKetQua.setText(ketQua + "");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Phải là số");
        }
    }//GEN-LAST:event_btnCongMouseClicked

    private void btnTruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTruMouseClicked
        try {

            String so1 = txtso1.getText();
            String so2 = txtso2.getText();
            if (so1.equals("") || so1.isEmpty() || so2.equals("") || so2.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please input your name");
            } else {
                float num1 = Float.parseFloat(so1);
                float num2 = Float.parseFloat(so2);
                float ketQua = num1 - num2;
                txtKetQua.setText(ketQua + "");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Phải là số");

        }
    }//GEN-LAST:event_btnTruMouseClicked

    private void btnNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanMouseClicked
        // TODO add your handling code here:
        try {

            String so1 = txtso1.getText();
            String so2 = txtso2.getText();
            if (so1.equals("") || so1.isEmpty() || so2.equals("") || so2.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please input your name");
            } else {
                float num1 = Float.parseFloat(so1);
                float num2 = Float.parseFloat(so2);
                float ketQua = num1 * num2;
                txtKetQua.setText(ketQua + "");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Phải là số");
        }
    }//GEN-LAST:event_btnNhanMouseClicked

    private void btnChiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChiaMouseClicked
        // TODO add your handling code here:
        try {

            String so1 = txtso1.getText();
            String so2 = txtso2.getText();
            if (so1.equals("") || so1.isEmpty() || so2.equals("") || so2.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please input your name");
                return;
            }

            float num1 = Float.parseFloat(so1);
            float num2 = Float.parseFloat(so2);
            if (num2 == 0) {
                JOptionPane.showMessageDialog(this, "Số phải khác 0");
                return;
            }
            float ketQua = num1 / num2;
            txtKetQua.setText(ketQua + "");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Phải là số");
        }
    }//GEN-LAST:event_btnChiaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChia;
    private javax.swing.JButton btnCong;
    private javax.swing.JButton btnNhan;
    private javax.swing.JButton btnTru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtKetQua;
    private javax.swing.JTextField txtso1;
    private javax.swing.JTextField txtso2;
    // End of variables declaration//GEN-END:variables
}
