/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.XeMay;
import service.Service;
import service.XeMayServiceImpl;

/**
 *
 * @author Hawin
 */
public class View extends javax.swing.JFrame {

    ArrayList<XeMay> list = new ArrayList<>();
    DefaultTableModel model;
    Service sev = new XeMayServiceImpl();

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        model = (DefaultTableModel) tblXeMay.getModel();
        loadData();
    }

    void loadData() {
        model.setRowCount(0);
        for (XeMay xm : sev.getAll()) {
            model.addRow(new Object[]{
                xm.getMa(),
                xm.getTen(),
                xm.getGiaNhap(),
                xm.getTrangThai() == 1 ? "InActive" : "Active"
            });
        }
    }

    XeMay getForm() {
        XeMay xm = new XeMay();
        xm.setMa(txtMA.getText());
        xm.setTen(txtTen.getText());
        xm.setGiaNhap(Double.valueOf(txtGiaNhap.getText()));
        xm.setTrangThai(cboTT.getSelectedIndex());
        return xm;
    }

    void setForm(XeMay xm) {
        txtMA.setText(xm.getMa());
        txtTen.setText(xm.getTen());
        txtGiaNhap.setText(xm.getGiaNhap() + "");
        cboTT.setSelectedIndex(xm.getTrangThai());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cboTT = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblXeMay = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Quản Lý Xe Máy");

        jLabel2.setText("Mã");

        jLabel3.setText("Giá nhập");

        jLabel4.setText("Tên xe");

        jLabel5.setText("Trạng thái");

        cboTT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "InActive" }));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        tblXeMay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã xe máy", "Tên xe máy", "Giá bán", "Trạng thái"
            }
        ));
        tblXeMay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblXeMayMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblXeMay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMA, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnThem)
                                    .addComponent(txtTen))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtGiaNhap)
                                    .addComponent(cboTT, 0, 113, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdate)
                                .addGap(60, 60, 60)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cboTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnUpdate))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            if (txtMA.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không được để trống mã");
                return;
            }
            if (txtTen.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không được để trống tên");
                return;
            }
            if (txtGiaNhap.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không được để trống giá");
                return;
            }
            double gia = Double.valueOf(txtGiaNhap.getText());
            if (gia < 0) {
                JOptionPane.showMessageDialog(this, "Giá phải dương");
                return;
            }
            int count = 0;
            for (XeMay xm : sev.getAll()) {
                if (txtMA.getText().equals(xm.getMa())) {
                    count++;
                }
            }
            if (count > 0) {
                JOptionPane.showMessageDialog(this, "Trùng mã, vui lòng nhập lại");
            } else {
                sev.add(getForm());
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                loadData();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Giá phải là 1 số");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblXeMayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblXeMayMouseClicked
        // TODO add your handling code here:
        int row = tblXeMay.getSelectedRow();
        if (row >= 0) {
            setForm(sev.getRow(row));
        }
    
    }//GEN-LAST:event_tblXeMayMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int row = tblXeMay.getSelectedRow();
        try {
            if (txtMA.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không được để trống mã");
                return;
            }
            if (txtTen.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không được để trống tên");
                return;
            }
            if (txtGiaNhap.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không được để trống giá");
                return;
            }
            double gia = Double.valueOf(txtGiaNhap.getText());
            if (gia < 0) {
                JOptionPane.showMessageDialog(this, "Giá phải dương");
                return;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Giá phải là 1 số");
        }
        if (row >= 0) {

            String ma = sev.getRow(row).getMa();
            XeMay xm = getForm();
            if (xm.getMa().equals(ma)) {
            xm.setMa(ma);
            sev.Update(xm);
            JOptionPane.showMessageDialog(this, "Update thành công");
            loadData();
            }
            else{
                JOptionPane.showMessageDialog(this, "UD thất bại");
            }
           

        } else {
            JOptionPane.showMessageDialog(this, "Chưa chọn dòng để update");
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboTT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblXeMay;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtMA;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
